version: 2

restore_node_modules: &restore_node_modules
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-dependencies-{{ .Branch }}-
      - v1-dependencies-

defaults: &defaults
  working_directory: ~/ci-setup
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

  test:
    docker:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      # run tests!
      - run:
          name: unit
          command: yarn test:unit
      - run:
          name: lint
          command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
